name: one_connect_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#----Utility Packages----#
  

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  get: ^4.6.6
  intl: ^0.19.0
  http: ^1.2.1
  logger: ^2.2.0
  url_launcher: ^6.2.6
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  page_transition: ^2.1.0
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.1.2
  faker: ^2.1.0
  csc_picker: ^0.2.7
  carousel_slider: ^4.2.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  photo_view: ^0.15.0
  timeago: ^3.7.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  uuid: ^3.0.6
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  awesome_notifications: ^0.9.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/onboarding/
    - assets/images/profile/
    - assets/images/donation/
    - assets/images/quotes/
    - assets/images/team/
    - assets/loading/


#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Light.ttf
#        - weight: 300
#        - asset: assets/fonts/Poppins-Regular.ttf
#        - weight: 400
#        - asset: assets/fonts/Poppins-Italic.ttf
#        - style: italic
#        - asset: assets/fonts/Poppins-Medium.ttf
#        - weight: 500
#        - asset: assets/fonts/Poppins-MediumItalic.ttf
#        - weight: 500
#        - style: italic
#        - asset: assets/fonts/Poppins-SemiBold.ttf
#        - weight: 600
#        - asset: assets/fonts/Poppins-Bold.ttf
#        - weight: 800

